namespace LrCatalogSync.UI
{
    partial class SettingsForm
    {
        private System.ComponentModel.IContainer components = null!;
        private System.Windows.Forms.ToolTip settingsToolTip = null!;
        private System.Windows.Forms.Panel scrollPanel = null!;
        private System.Windows.Forms.Panel buttonPanel = null!;
        private System.Windows.Forms.Label titleLabel = null!;
        private System.Windows.Forms.Label separatorLabel1 = null!;
        private System.Windows.Forms.Label separatorLabel2 = null!;
        private System.Windows.Forms.CheckBox chkAutoRun = null!;
        private System.Windows.Forms.Label rcloneFolderLabel = null!;
        private System.Windows.Forms.TextBox txtRcloneFolder = null!;
        private System.Windows.Forms.Button browseRcloneFolderButton = null!;
        private System.Windows.Forms.Label rcloneDownloadLabel = null!;
        private System.Windows.Forms.Label logLevelLabel = null!;
        private System.Windows.Forms.ComboBox cmbLogLevel = null!;
        private System.Windows.Forms.Label updateIntervalLabel = null!;
        private System.Windows.Forms.TextBox txtGlobalCycleInterval = null!;
        private System.Windows.Forms.Label secondsLabel = null!;
        private System.Windows.Forms.Label catalogHeadingLabel = null!;
        private System.Windows.Forms.Label catalogSeparatorLabel = null!;
        private System.Windows.Forms.CheckBox chkSyncPreviewData = null!;
        private System.Windows.Forms.Label catalogLocalFileLabel = null!;
        private System.Windows.Forms.TextBox txtCatalogLocalFile = null!;
        private System.Windows.Forms.Button browseCatalogFileButton = null!;
        private System.Windows.Forms.Label catalogRemotePathLabel = null!;
        private System.Windows.Forms.TextBox txtCatalogRemotePath = null!;
        private System.Windows.Forms.CheckBox chkEnableRcloneCopy = null!;
        private System.Windows.Forms.Label rcloneCopyFolderNameLabel = null!;
        private System.Windows.Forms.TextBox txtRcloneCopyFolderName = null!;
        private System.Windows.Forms.Label backupHeadingLabel = null!;
        private System.Windows.Forms.Label backupSeparatorLabel = null!;
        private System.Windows.Forms.CheckBox chkEnableBackups = null!;
        private System.Windows.Forms.Label backupsLocalPathLabel = null!;
        private System.Windows.Forms.TextBox txtBackupsLocalPath = null!;
        private System.Windows.Forms.Button browseBackupsPathButton = null!;
        private System.Windows.Forms.Label backupsRemotePathLabel = null!;
        private System.Windows.Forms.TextBox txtBackupsRemotePath = null!;
        private System.Windows.Forms.Label sambaHeadingLabel = null!;
        private System.Windows.Forms.Label sambaSeparatorLabel = null!;
        private System.Windows.Forms.Label remoteIpLabel = null!;
        private System.Windows.Forms.TextBox txtRemoteIP = null!;
        private System.Windows.Forms.Label sambaUserLabel = null!;
        private System.Windows.Forms.TextBox txtSambaUser = null!;
        private System.Windows.Forms.Label sambaPasswordLabel = null!;
        private System.Windows.Forms.TextBox txtSambaPassword = null!;
        private System.Windows.Forms.LinkLabel gitHubLinkLabel = null!;
        private System.Windows.Forms.LinkLabel websiteLinkLabel = null!;
        private System.Windows.Forms.Button saveButton = null!;
        private System.Windows.Forms.Button cancelButton = null!;

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                components?.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            settingsToolTip = new System.Windows.Forms.ToolTip(components);
            scrollPanel = new System.Windows.Forms.Panel();
            buttonPanel = new System.Windows.Forms.Panel();
            titleLabel = new System.Windows.Forms.Label();
            separatorLabel1 = new System.Windows.Forms.Label();
            separatorLabel2 = new System.Windows.Forms.Label();
            chkAutoRun = new System.Windows.Forms.CheckBox();
            rcloneFolderLabel = new System.Windows.Forms.Label();
            txtRcloneFolder = new System.Windows.Forms.TextBox();
            browseRcloneFolderButton = new System.Windows.Forms.Button();
            rcloneDownloadLabel = new System.Windows.Forms.Label();
            logLevelLabel = new System.Windows.Forms.Label();
            cmbLogLevel = new System.Windows.Forms.ComboBox();
            updateIntervalLabel = new System.Windows.Forms.Label();
            txtGlobalCycleInterval = new System.Windows.Forms.TextBox();
            secondsLabel = new System.Windows.Forms.Label();
            catalogHeadingLabel = new System.Windows.Forms.Label();
            catalogSeparatorLabel = new System.Windows.Forms.Label();
            chkSyncPreviewData = new System.Windows.Forms.CheckBox();
            catalogLocalFileLabel = new System.Windows.Forms.Label();
            txtCatalogLocalFile = new System.Windows.Forms.TextBox();
            browseCatalogFileButton = new System.Windows.Forms.Button();
            catalogRemotePathLabel = new System.Windows.Forms.Label();
            txtCatalogRemotePath = new System.Windows.Forms.TextBox();
            chkEnableRcloneCopy = new System.Windows.Forms.CheckBox();
            rcloneCopyFolderNameLabel = new System.Windows.Forms.Label();
            txtRcloneCopyFolderName = new System.Windows.Forms.TextBox();
            backupHeadingLabel = new System.Windows.Forms.Label();
            backupSeparatorLabel = new System.Windows.Forms.Label();
            chkEnableBackups = new System.Windows.Forms.CheckBox();
            backupsLocalPathLabel = new System.Windows.Forms.Label();
            txtBackupsLocalPath = new System.Windows.Forms.TextBox();
            browseBackupsPathButton = new System.Windows.Forms.Button();
            backupsRemotePathLabel = new System.Windows.Forms.Label();
            txtBackupsRemotePath = new System.Windows.Forms.TextBox();
            sambaHeadingLabel = new System.Windows.Forms.Label();
            sambaSeparatorLabel = new System.Windows.Forms.Label();
            remoteIpLabel = new System.Windows.Forms.Label();
            txtRemoteIP = new System.Windows.Forms.TextBox();
            sambaUserLabel = new System.Windows.Forms.Label();
            txtSambaUser = new System.Windows.Forms.TextBox();
            sambaPasswordLabel = new System.Windows.Forms.Label();
            txtSambaPassword = new System.Windows.Forms.TextBox();
            gitHubLinkLabel = new System.Windows.Forms.LinkLabel();
            websiteLinkLabel = new System.Windows.Forms.LinkLabel();
            saveButton = new System.Windows.Forms.Button();
            cancelButton = new System.Windows.Forms.Button();
            //
            // Scrollbarer Einstellungsbereich
            //
            scrollPanel.AutoScroll = true;
            scrollPanel.Location = new System.Drawing.Point(0, 0);
            scrollPanel.Size = new System.Drawing.Size(496, 552);
            scrollPanel.Dock = System.Windows.Forms.DockStyle.None;
            scrollPanel.Padding = new System.Windows.Forms.Padding(10);
            scrollPanel.Controls.Add(titleLabel);
            scrollPanel.Controls.Add(separatorLabel1);
            scrollPanel.Controls.Add(separatorLabel2);
            scrollPanel.Controls.Add(chkAutoRun);
            scrollPanel.Controls.Add(rcloneFolderLabel);
            scrollPanel.Controls.Add(txtRcloneFolder);
            scrollPanel.Controls.Add(browseRcloneFolderButton);
            scrollPanel.Controls.Add(rcloneDownloadLabel);
            scrollPanel.Controls.Add(logLevelLabel);
            scrollPanel.Controls.Add(cmbLogLevel);
            scrollPanel.Controls.Add(updateIntervalLabel);
            scrollPanel.Controls.Add(txtGlobalCycleInterval);
            scrollPanel.Controls.Add(secondsLabel);
            scrollPanel.Controls.Add(catalogHeadingLabel);
            scrollPanel.Controls.Add(catalogSeparatorLabel);
            scrollPanel.Controls.Add(chkSyncPreviewData);
            scrollPanel.Controls.Add(catalogLocalFileLabel);
            scrollPanel.Controls.Add(txtCatalogLocalFile);
            scrollPanel.Controls.Add(browseCatalogFileButton);
            scrollPanel.Controls.Add(catalogRemotePathLabel);
            scrollPanel.Controls.Add(txtCatalogRemotePath);
            scrollPanel.Controls.Add(chkEnableRcloneCopy);
            scrollPanel.Controls.Add(rcloneCopyFolderNameLabel);
            scrollPanel.Controls.Add(txtRcloneCopyFolderName);
            scrollPanel.Controls.Add(backupHeadingLabel);
            scrollPanel.Controls.Add(backupSeparatorLabel);
            scrollPanel.Controls.Add(chkEnableBackups);
            scrollPanel.Controls.Add(backupsLocalPathLabel);
            scrollPanel.Controls.Add(txtBackupsLocalPath);
            scrollPanel.Controls.Add(browseBackupsPathButton);
            scrollPanel.Controls.Add(backupsRemotePathLabel);
            scrollPanel.Controls.Add(txtBackupsRemotePath);
            scrollPanel.Controls.Add(sambaHeadingLabel);
            scrollPanel.Controls.Add(sambaSeparatorLabel);
            scrollPanel.Controls.Add(remoteIpLabel);
            scrollPanel.Controls.Add(txtRemoteIP);
            scrollPanel.Controls.Add(sambaUserLabel);
            scrollPanel.Controls.Add(txtSambaUser);
            scrollPanel.Controls.Add(sambaPasswordLabel);
            scrollPanel.Controls.Add(txtSambaPassword);
            //
            // Formularüberschrift und Trenner
            //
            titleLabel.AutoSize = false;
            titleLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            titleLabel.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            titleLabel.Location = new System.Drawing.Point(10, 6);
            titleLabel.Size = new System.Drawing.Size(300, 20);
            titleLabel.Text = "LrCatalogSync - Einstellungen";
            separatorLabel1.AutoSize = false;
            separatorLabel1.Anchor = System.Windows.Forms.AnchorStyles.None;
            separatorLabel1.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            separatorLabel1.Location = new System.Drawing.Point(12, 15);
            separatorLabel1.Size = new System.Drawing.Size(296, 16);
            separatorLabel1.Text = "_________________________________________________________________________";
            separatorLabel2.AutoSize = false;
            separatorLabel2.Anchor = System.Windows.Forms.AnchorStyles.None;
            separatorLabel2.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            separatorLabel2.Location = new System.Drawing.Point(10, 20);
            separatorLabel2.Size = new System.Drawing.Size(300, 20);
            separatorLabel2.Text = "_________________________________________________________________________";
            //
            // Allgemeine Einstellungen
            //
            chkAutoRun.Name = "chkAutoRun";
            chkAutoRun.Location = new System.Drawing.Point(160, 60);
            chkAutoRun.Size = new System.Drawing.Size(300, 20);
            chkAutoRun.Text = "Automatisch beim Systemstart ausführen";
            settingsToolTip.SetToolTip(chkAutoRun, "Startet LrCatalogSync automatisch beim Windows-Systemstart.");
            rcloneFolderLabel.AutoSize = false;
            rcloneFolderLabel.Location = new System.Drawing.Point(10, 85);
            rcloneFolderLabel.Size = new System.Drawing.Size(140, 20);
            rcloneFolderLabel.Text = "Rclone Verzeichnispfad:";
            txtRcloneFolder.Name = "txtRcloneFolder";
            txtRcloneFolder.Location = new System.Drawing.Point(150, 85);
            txtRcloneFolder.Size = new System.Drawing.Size(300, 24);
            settingsToolTip.SetToolTip(txtRcloneFolder, "Pfad zur rclone-Installation oder zum rclone-Verzeichnis.");
            browseRcloneFolderButton.Location = new System.Drawing.Point(450, 85);
            browseRcloneFolderButton.Size = new System.Drawing.Size(35, 24);
            browseRcloneFolderButton.Text = "...";
            browseRcloneFolderButton.Tag = txtRcloneFolder;
            browseRcloneFolderButton.Click += new System.EventHandler(BrowseButton_Click);
            rcloneDownloadLabel.AutoSize = false;
            rcloneDownloadLabel.Cursor = System.Windows.Forms.Cursors.Hand;
            rcloneDownloadLabel.ForeColor = System.Drawing.Color.FromArgb(0, 120, 215);
            rcloneDownloadLabel.Location = new System.Drawing.Point(150, 107);
            rcloneDownloadLabel.Size = new System.Drawing.Size(300, 20);
            rcloneDownloadLabel.Text = "Download von rclone (https://rclone.org/downloads)";
            rcloneDownloadLabel.Click += new System.EventHandler(RcloneDownloadLabel_Click);
            logLevelLabel.AutoSize = false;
            logLevelLabel.Location = new System.Drawing.Point(10, 132);
            logLevelLabel.Size = new System.Drawing.Size(140, 20);
            logLevelLabel.Text = "Log-Level:";
            cmbLogLevel.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            cmbLogLevel.Items.AddRange(new object[] { "DEBUG", "INFO", "NOTICE", "ERROR" });
            cmbLogLevel.Location = new System.Drawing.Point(150, 132);
            cmbLogLevel.Size = new System.Drawing.Size(100, 24);
            updateIntervalLabel.AutoSize = false;
            updateIntervalLabel.Location = new System.Drawing.Point(10, 157);
            updateIntervalLabel.Size = new System.Drawing.Size(140, 20);
            updateIntervalLabel.Text = "Aktuallisierungszeit:";
            txtGlobalCycleInterval.Name = "txtGlobalCycleInterval";
            txtGlobalCycleInterval.Location = new System.Drawing.Point(150, 157);
            txtGlobalCycleInterval.Size = new System.Drawing.Size(35, 24);
            txtGlobalCycleInterval.TextAlign = System.Windows.Forms.HorizontalAlignment.Right;
            settingsToolTip.SetToolTip(txtGlobalCycleInterval, "Zeit in Sekunden zwischen den automatischen Synchronisationszyklen (1 bis 999).");
            secondsLabel.AutoSize = false;
            secondsLabel.Anchor = System.Windows.Forms.AnchorStyles.None;
            secondsLabel.Location = new System.Drawing.Point(185, 158);
            secondsLabel.Size = new System.Drawing.Size(70, 20);
            secondsLabel.Text = "Sekunden";
            //
            // Lightroom-Katalog
            //
            catalogHeadingLabel.AutoSize = false;
            catalogHeadingLabel.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            catalogHeadingLabel.Location = new System.Drawing.Point(10, 182);
            catalogHeadingLabel.Size = new System.Drawing.Size(300, 20);
            catalogHeadingLabel.Text = "Lightroom Katalog";
            catalogSeparatorLabel.AutoSize = false;
            catalogSeparatorLabel.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            catalogSeparatorLabel.Location = new System.Drawing.Point(10, 190);
            catalogSeparatorLabel.Size = new System.Drawing.Size(300, 20);
            catalogSeparatorLabel.Text = "_________________________________________________________________________";
            chkSyncPreviewData.Name = "chkSyncPreviewData";
            chkSyncPreviewData.Location = new System.Drawing.Point(160, 210);
            chkSyncPreviewData.Size = new System.Drawing.Size(300, 20);
            chkSyncPreviewData.Text = "*Previews.lrdata synchronisieren?";
            settingsToolTip.SetToolTip(chkSyncPreviewData, "Wenn aktiv, wird zusätzlich der Ordner *Previews.lrdata des Lightroom-Katalogs synchronisiert.");
            catalogLocalFileLabel.AutoSize = false;
            catalogLocalFileLabel.Location = new System.Drawing.Point(10, 237);
            catalogLocalFileLabel.Size = new System.Drawing.Size(140, 20);
            catalogLocalFileLabel.Text = "lokale Katalog Datei:";
            txtCatalogLocalFile.Name = "txtCatalogLocalFile";
            txtCatalogLocalFile.Location = new System.Drawing.Point(150, 237);
            txtCatalogLocalFile.Size = new System.Drawing.Size(300, 24);
            settingsToolTip.SetToolTip(txtCatalogLocalFile, "Lokaler Pfad zur Lightroom-Katalogdatei (.lrcat).");
            browseCatalogFileButton.Location = new System.Drawing.Point(450, 237);
            browseCatalogFileButton.Size = new System.Drawing.Size(35, 24);
            browseCatalogFileButton.Text = "...";
            browseCatalogFileButton.Tag = txtCatalogLocalFile;
            browseCatalogFileButton.Click += new System.EventHandler(BrowseButton_Click);
            catalogRemotePathLabel.AutoSize = false;
            catalogRemotePathLabel.Location = new System.Drawing.Point(10, 262);
            catalogRemotePathLabel.Size = new System.Drawing.Size(140, 20);
            catalogRemotePathLabel.Text = "Remote Katalog Pfad:";
            txtCatalogRemotePath.Name = "txtCatalogRemotePath";
            txtCatalogRemotePath.Location = new System.Drawing.Point(150, 262);
            txtCatalogRemotePath.Size = new System.Drawing.Size(300, 24);
            settingsToolTip.SetToolTip(txtCatalogRemotePath, "Zielpfad auf dem Samba-Server z.B. //192.168.1.100/SambaOrdner/ -> /SambaOrdner/");
            chkEnableRcloneCopy.Name = "chkEnableRcloneCopy";
            chkEnableRcloneCopy.Location = new System.Drawing.Point(160, 287);
            chkEnableRcloneCopy.Size = new System.Drawing.Size(300, 20);
            chkEnableRcloneCopy.Text = "letzten Katalog behalten?";
            settingsToolTip.SetToolTip(chkEnableRcloneCopy, "Behält nach der Synchronisation eine Kopie des letzten Katalogs.");
            rcloneCopyFolderNameLabel.AutoSize = false;
            rcloneCopyFolderNameLabel.Location = new System.Drawing.Point(10, 312);
            rcloneCopyFolderNameLabel.Size = new System.Drawing.Size(140, 20);
            rcloneCopyFolderNameLabel.Text = "Ordnername:";
            txtRcloneCopyFolderName.Name = "txtRcloneCopyFolderName";
            txtRcloneCopyFolderName.Location = new System.Drawing.Point(150, 312);
            txtRcloneCopyFolderName.Size = new System.Drawing.Size(300, 24);
            settingsToolTip.SetToolTip(txtRcloneCopyFolderName, "Name des Ordners für die Kopie des letzten Lightroom-Katalogs.");
            //
            // Lightroom-Katalog-Sicherungsordner
            //
            backupHeadingLabel.AutoSize = false;
            backupHeadingLabel.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            backupHeadingLabel.Location = new System.Drawing.Point(10, 337);
            backupHeadingLabel.Size = new System.Drawing.Size(320, 20);
            backupHeadingLabel.Text = "Lightroom Katalog Sicherungsordner";
            backupSeparatorLabel.AutoSize = false;
            backupSeparatorLabel.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            backupSeparatorLabel.Location = new System.Drawing.Point(10, 345);
            backupSeparatorLabel.Size = new System.Drawing.Size(300, 20);
            backupSeparatorLabel.Text = "_________________________________________________________________________";
            chkEnableBackups.Name = "chkEnableBackups";
            chkEnableBackups.Location = new System.Drawing.Point(160, 365);
            chkEnableBackups.Size = new System.Drawing.Size(300, 20);
            chkEnableBackups.Text = "Sicherungsordner aktivieren";
            settingsToolTip.SetToolTip(chkEnableBackups, "Aktiviert die Sicherung der Sicherungsordner die Lightroom Classic ablegt.");
            backupsLocalPathLabel.AutoSize = false;
            backupsLocalPathLabel.Location = new System.Drawing.Point(10, 392);
            backupsLocalPathLabel.Size = new System.Drawing.Size(140, 20);
            backupsLocalPathLabel.Text = "Lokaler Backup Pfad:";
            txtBackupsLocalPath.Name = "txtBackupsLocalPath";
            txtBackupsLocalPath.Location = new System.Drawing.Point(150, 392);
            txtBackupsLocalPath.Size = new System.Drawing.Size(300, 24);
            settingsToolTip.SetToolTip(txtBackupsLocalPath, "Lokaler Pfad zum Sicherungsordner von Lightroom Classic.");
            browseBackupsPathButton.Location = new System.Drawing.Point(450, 392);
            browseBackupsPathButton.Size = new System.Drawing.Size(35, 24);
            browseBackupsPathButton.Text = "...";
            browseBackupsPathButton.Tag = txtBackupsLocalPath;
            browseBackupsPathButton.Click += new System.EventHandler(BrowseButton_Click);
            backupsRemotePathLabel.AutoSize = false;
            backupsRemotePathLabel.Location = new System.Drawing.Point(10, 417);
            backupsRemotePathLabel.Size = new System.Drawing.Size(140, 20);
            backupsRemotePathLabel.Text = "Remote Backup Pfad:";
            txtBackupsRemotePath.Name = "txtBackupsRemotePath";
            txtBackupsRemotePath.Location = new System.Drawing.Point(150, 417);
            txtBackupsRemotePath.Size = new System.Drawing.Size(300, 24);
            settingsToolTip.SetToolTip(txtBackupsRemotePath, "Zielpfad auf dem entfernten Speicher für die Sicherungsordner von Lightroom Classic.");
            //
            // Samba-Server-Einstellungen
            //
            sambaHeadingLabel.AutoSize = false;
            sambaHeadingLabel.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            sambaHeadingLabel.Location = new System.Drawing.Point(10, 442);
            sambaHeadingLabel.Size = new System.Drawing.Size(300, 20);
            sambaHeadingLabel.Text = "Samba Server Einstellungen";
            sambaSeparatorLabel.AutoSize = false;
            sambaSeparatorLabel.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            sambaSeparatorLabel.Location = new System.Drawing.Point(10, 450);
            sambaSeparatorLabel.Size = new System.Drawing.Size(300, 20);
            sambaSeparatorLabel.Text = "________________________________________________________________________________________________";
            remoteIpLabel.AutoSize = false;
            remoteIpLabel.Location = new System.Drawing.Point(10, 470);
            remoteIpLabel.Size = new System.Drawing.Size(140, 20);
            remoteIpLabel.Text = "Server IP/Name:";
            txtRemoteIP.Name = "txtRemoteIP";
            txtRemoteIP.Location = new System.Drawing.Point(150, 470);
            txtRemoteIP.Size = new System.Drawing.Size(300, 24);
            settingsToolTip.SetToolTip(txtRemoteIP, "IP-Adresse oder Hostname des Samba-Servers.");
            sambaUserLabel.AutoSize = false;
            sambaUserLabel.Location = new System.Drawing.Point(10, 495);
            sambaUserLabel.Size = new System.Drawing.Size(140, 20);
            sambaUserLabel.Text = "Benutzername:";
            txtSambaUser.Name = "txtSambaUser";
            txtSambaUser.Location = new System.Drawing.Point(150, 495);
            txtSambaUser.Size = new System.Drawing.Size(300, 24);
            settingsToolTip.SetToolTip(txtSambaUser, "Benutzername für die Verbindung zum Samba-Server.");
            sambaPasswordLabel.AutoSize = false;
            sambaPasswordLabel.Location = new System.Drawing.Point(10, 520);
            sambaPasswordLabel.Size = new System.Drawing.Size(140, 20);
            sambaPasswordLabel.Text = "Passwort:";
            txtSambaPassword.Name = "txtSambaPassword";
            txtSambaPassword.Location = new System.Drawing.Point(150, 520);
            txtSambaPassword.Size = new System.Drawing.Size(300, 24);
            txtSambaPassword.UseSystemPasswordChar = true;
            settingsToolTip.SetToolTip(txtSambaPassword, "Passwort für die Verbindung zum Samba-Server.");
            //
            // Fußbereich
            //
            buttonPanel.BackColor = System.Drawing.SystemColors.Control;
            buttonPanel.Size = new System.Drawing.Size(496, 64);
            buttonPanel.Location = new System.Drawing.Point(0, 552);
            buttonPanel.Padding = new System.Windows.Forms.Padding(0, 100, 0, 0);
            buttonPanel.AutoSize = true;
            buttonPanel.Anchor = System.Windows.Forms.AnchorStyles.None;
            buttonPanel.Dock = System.Windows.Forms.DockStyle.None;
            buttonPanel.Height = 60;
            buttonPanel.Controls.Add(gitHubLinkLabel);
            buttonPanel.Controls.Add(websiteLinkLabel);
            buttonPanel.Controls.Add(saveButton);
            buttonPanel.Controls.Add(cancelButton);
            gitHubLinkLabel.AutoSize = false;
            gitHubLinkLabel.LinkBehavior = System.Windows.Forms.LinkBehavior.NeverUnderline;
            gitHubLinkLabel.LinkColor = System.Drawing.Color.FromArgb(0, 120, 215);
            gitHubLinkLabel.VisitedLinkColor = System.Drawing.Color.FromArgb(0, 120, 215);
            gitHubLinkLabel.Location = new System.Drawing.Point(10, 15);
            gitHubLinkLabel.Size = new System.Drawing.Size(230, 20);
            gitHubLinkLabel.Text = "GitHub Project";
            gitHubLinkLabel.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(GitHubLinkLabel_LinkClicked);
            websiteLinkLabel.AutoSize = false;
            websiteLinkLabel.LinkBehavior = System.Windows.Forms.LinkBehavior.NeverUnderline;
            websiteLinkLabel.LinkColor = System.Drawing.Color.FromArgb(0, 120, 215);
            websiteLinkLabel.VisitedLinkColor = System.Drawing.Color.FromArgb(0, 120, 215);
            websiteLinkLabel.Location = new System.Drawing.Point(10, 35);
            websiteLinkLabel.Size = new System.Drawing.Size(230, 20);
            websiteLinkLabel.Text = "© Fototour und Technik";
            websiteLinkLabel.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(WebsiteLinkLabel_LinkClicked);
            saveButton.Location = new System.Drawing.Point(265, 12);
            saveButton.Size = new System.Drawing.Size(100, 35);
            saveButton.Text = "Speichern";
            saveButton.Click += new System.EventHandler(BtnSave_Click);
            cancelButton.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            cancelButton.Location = new System.Drawing.Point(380, 12);
            cancelButton.Size = new System.Drawing.Size(100, 35);
            cancelButton.Text = "Abbrechen";
            //
            // SettingsForm
            //
            AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            Font = new System.Drawing.Font("Segoe UI", 9F);
            ClientSize = new System.Drawing.Size(496, 608);
            Controls.Add(scrollPanel);
            Controls.Add(buttonPanel);
            FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            MaximizeBox = false;
            MinimizeBox = true;
            Name = "SettingsForm";
            StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            Text = "LrCatalogSync - Einstellungen";
            CancelButton = cancelButton;
        }
    }
}
