//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

namespace LrCatalogSync.Resources.Strings
{
    using System.Globalization;
    using System.Resources;

    internal static class Strings
    {
        private static ResourceManager? resourceManager;

        internal static ResourceManager ResourceManager => resourceManager ??= new ResourceManager(
            "LrCatalogSync.Resources.Strings.Strings",
            typeof(Strings).Assembly);

        internal static CultureInfo? Culture { get; set; }

        internal static string Language_SystemWindows => GetString(nameof(Language_SystemWindows));
        internal static string Tray_Tip_Start => GetString(nameof(Tray_Tip_Start));
        internal static string Tray_Tip_NoCfg => GetString(nameof(Tray_Tip_NoCfg));
        internal static string Tray_Tip_Standby => GetString(nameof(Tray_Tip_Standby));
        internal static string Tray_Tip_BSyncing => GetString(nameof(Tray_Tip_BSyncing));
        internal static string Tray_Tip_LSyncing => GetString(nameof(Tray_Tip_LSyncing));
        internal static string Tray_Tip_RcloneCfg => GetString(nameof(Tray_Tip_RcloneCfg));
        internal static string Tray_Tip_RcloneExe => GetString(nameof(Tray_Tip_RcloneExe));
        internal static string Tray_Tip_Error => GetString(nameof(Tray_Tip_Error));
        internal static string Tray_Tip_Lockfile => GetString(nameof(Tray_Tip_Lockfile));
        internal static string Tray_Tip_NoSamba => GetString(nameof(Tray_Tip_NoSamba));
        internal static string Tray_Tip_RemoteLockfileDown => GetString(nameof(Tray_Tip_RemoteLockfileDown));
        internal static string Tray_Tip_RemoteLockfileUp => GetString(nameof(Tray_Tip_RemoteLockfileUp));
        internal static string Tray_Tip_RemoteLightroom => GetString(nameof(Tray_Tip_RemoteLightroom));
        internal static string Tray_Tip_LockfileErr => GetString(nameof(Tray_Tip_LockfileErr));
        internal static string Tray_Tip_CrashRecovery => GetString(nameof(Tray_Tip_CrashRecovery));
        internal static string Tray_Tip_SyncDisabled => GetString(nameof(Tray_Tip_SyncDisabled));
        internal static string Tray_Menu_UsbExport => GetString(nameof(Tray_Menu_UsbExport));
        internal static string Tray_Menu_TurnOff => GetString(nameof(Tray_Menu_TurnOff));
        internal static string Tray_Menu_TurnOn => GetString(nameof(Tray_Menu_TurnOn));
        internal static string Tray_Menu_UsbExportOpen => GetString(nameof(Tray_Menu_UsbExportOpen));
        internal static string Tray_Menu_Settings => GetString(nameof(Tray_Menu_Settings));
        internal static string Tray_Menu_Exit => GetString(nameof(Tray_Menu_Exit));
        internal static string Settings_Title => GetString(nameof(Settings_Title));
        internal static string Settings_Group_General => GetString(nameof(Settings_Group_General));
        internal static string Settings_AutoRun => GetString(nameof(Settings_AutoRun));
        internal static string Settings_RcloneFolder => GetString(nameof(Settings_RcloneFolder));
        internal static string Settings_RcloneDownload => GetString(nameof(Settings_RcloneDownload));
        internal static string Settings_LogLevel => GetString(nameof(Settings_LogLevel));
        internal static string Settings_Language => GetString(nameof(Settings_Language));
        internal static string Settings_UpdateInterval => GetString(nameof(Settings_UpdateInterval));
        internal static string Settings_Seconds => GetString(nameof(Settings_Seconds));
        internal static string Settings_Group_Catalog => GetString(nameof(Settings_Group_Catalog));
        internal static string Settings_SyncPreviews => GetString(nameof(Settings_SyncPreviews));
        internal static string Settings_CatalogLocal => GetString(nameof(Settings_CatalogLocal));
        internal static string Settings_CatalogRemote => GetString(nameof(Settings_CatalogRemote));
        internal static string Settings_KeepCatalog => GetString(nameof(Settings_KeepCatalog));
        internal static string Settings_FolderName => GetString(nameof(Settings_FolderName));
        internal static string Settings_Group_Backups => GetString(nameof(Settings_Group_Backups));
        internal static string Settings_SyncBackups => GetString(nameof(Settings_SyncBackups));
        internal static string Settings_BackupLocal => GetString(nameof(Settings_BackupLocal));
        internal static string Settings_BackupRemote => GetString(nameof(Settings_BackupRemote));
        internal static string Settings_Group_Samba => GetString(nameof(Settings_Group_Samba));
        internal static string Settings_Server => GetString(nameof(Settings_Server));
        internal static string Settings_Username => GetString(nameof(Settings_Username));
        internal static string Settings_Password => GetString(nameof(Settings_Password));
        internal static string Settings_Save => GetString(nameof(Settings_Save));
        internal static string Settings_Cancel => GetString(nameof(Settings_Cancel));
        internal static string Settings_Tip_AutoRun => GetString(nameof(Settings_Tip_AutoRun));
        internal static string Settings_Tip_RcloneFolder => GetString(nameof(Settings_Tip_RcloneFolder));
        internal static string Settings_Tip_Interval => GetString(nameof(Settings_Tip_Interval));
        internal static string Settings_Tip_SyncPreviews => GetString(nameof(Settings_Tip_SyncPreviews));
        internal static string Settings_Tip_CatalogLocal => GetString(nameof(Settings_Tip_CatalogLocal));
        internal static string Settings_Tip_CatalogRemote => GetString(nameof(Settings_Tip_CatalogRemote));
        internal static string Settings_Tip_KeepCatalog => GetString(nameof(Settings_Tip_KeepCatalog));
        internal static string Settings_Tip_FolderName => GetString(nameof(Settings_Tip_FolderName));
        internal static string Settings_Tip_SyncBackups => GetString(nameof(Settings_Tip_SyncBackups));
        internal static string Settings_Tip_BackupLocal => GetString(nameof(Settings_Tip_BackupLocal));
        internal static string Settings_Tip_BackupRemote => GetString(nameof(Settings_Tip_BackupRemote));
        internal static string Settings_Tip_Server => GetString(nameof(Settings_Tip_Server));
        internal static string Settings_Tip_Username => GetString(nameof(Settings_Tip_Username));
        internal static string Settings_Tip_Password => GetString(nameof(Settings_Tip_Password));
        internal static string Settings_Filter_Catalog => GetString(nameof(Settings_Filter_Catalog));
        internal static string Settings_Dialog_SelectFolder => GetString(nameof(Settings_Dialog_SelectFolder));
        internal static string Settings_Dialog_SelectFile => GetString(nameof(Settings_Dialog_SelectFile));
        internal static string Settings_Dialog_LinkError => GetString(nameof(Settings_Dialog_LinkError));
        internal static string Settings_Title_Error => GetString(nameof(Settings_Title_Error));
        internal static string Settings_Dialog_InvalidInterval => GetString(nameof(Settings_Dialog_InvalidInterval));
        internal static string Settings_Dialog_InvalidIntervalTitle => GetString(nameof(Settings_Dialog_InvalidIntervalTitle));
        internal static string Settings_Dialog_IntervalRange => GetString(nameof(Settings_Dialog_IntervalRange));
        internal static string Settings_Dialog_IntervalRangeTitle => GetString(nameof(Settings_Dialog_IntervalRangeTitle));
        internal static string Settings_Dialog_RcloneMissing => GetString(nameof(Settings_Dialog_RcloneMissing));
        internal static string Settings_Dialog_RcloneMissingTitle => GetString(nameof(Settings_Dialog_RcloneMissingTitle));
        internal static string Settings_Dialog_CatalogRequired => GetString(nameof(Settings_Dialog_CatalogRequired));
        internal static string Settings_Dialog_CatalogRequiredTitle => GetString(nameof(Settings_Dialog_CatalogRequiredTitle));
        internal static string Settings_Dialog_CatalogMissing => GetString(nameof(Settings_Dialog_CatalogMissing));
        internal static string Settings_Dialog_CatalogMissingTitle => GetString(nameof(Settings_Dialog_CatalogMissingTitle));
        internal static string Settings_Dialog_CatalogInvalid => GetString(nameof(Settings_Dialog_CatalogInvalid));
        internal static string Settings_Dialog_CatalogInvalidTitle => GetString(nameof(Settings_Dialog_CatalogInvalidTitle));
        internal static string Settings_Dialog_BackupLocalRequired => GetString(nameof(Settings_Dialog_BackupLocalRequired));
        internal static string Settings_Dialog_BackupLocalRequiredTitle => GetString(nameof(Settings_Dialog_BackupLocalRequiredTitle));
        internal static string Settings_Dialog_BackupLocalMissing => GetString(nameof(Settings_Dialog_BackupLocalMissing));
        internal static string Settings_Dialog_BackupLocalMissingTitle => GetString(nameof(Settings_Dialog_BackupLocalMissingTitle));
        internal static string Settings_Dialog_BackupRemoteRequired => GetString(nameof(Settings_Dialog_BackupRemoteRequired));
        internal static string Settings_Dialog_BackupRemoteRequiredTitle => GetString(nameof(Settings_Dialog_BackupRemoteRequiredTitle));
        internal static string Settings_Dialog_CopyFolderRequired => GetString(nameof(Settings_Dialog_CopyFolderRequired));
        internal static string Settings_Dialog_CopyFolderRequiredTitle => GetString(nameof(Settings_Dialog_CopyFolderRequiredTitle));
        internal static string Settings_Dialog_SaveSuccess => GetString(nameof(Settings_Dialog_SaveSuccess));
        internal static string Settings_Title_Success => GetString(nameof(Settings_Title_Success));
        internal static string Settings_Dialog_SaveFailure => GetString(nameof(Settings_Dialog_SaveFailure));
        internal static string Settings_Dialog_RemotePathInvalid => GetString(nameof(Settings_Dialog_RemotePathInvalid));
        internal static string Settings_Dialog_RemotePathInvalidTitle => GetString(nameof(Settings_Dialog_RemotePathInvalidTitle));
        internal static string Settings_Debug_TextTooWide => GetString(nameof(Settings_Debug_TextTooWide));

        internal static string Get(string name) => GetString(name);

        private static string GetString(string name) => ResourceManager.GetString(name, Culture) ?? name;
    }
}