LocalPath=E:\Lightroom_test
BackupsAbsolutePath=
EnableBackups=False
RemotePath=/Lightroom/
RcloneFolder=C:\Users\Raychan\Desktop\rclone
RemoteIP=192.168.178.5
SambaUser=RaySamba
SambaPassword=MefZOJAZIrBCaLN2gA51LnmkEW_hBbDlf3EXPBM
LogLevel=Debug
